@startuml 
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Администратор")
Person(moderator, "Модератор")
Person(user, "Пользователь")

System(conference_site, "Интернет-Магазин", "Лучше чем Wildberries")

Rel(admin, conference_site, "Просмотр, добавление и редактирование информации  пользователей, просмотр/редактирование заказов , редактирование и просмотр карточек товара")
Rel(moderator, conference_site, "Модерация карточек товаров и пользователей")
Rel(user, conference_site, "Регистрация, просмотр покупок, добавление/удаление товаров из корзины, оплата")
@enduml